apiVersion: v1
kind: Service
metadata:
  name: cors-proxy-service
  namespace: aks-cluster
spec:
  type: LoadBalancer
  selector:
    app: cors-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080